const { withProguardRule, withDangerousMod } = require('@expo/config-plugins');

const withRazorpayProguard = (config) => {
    return withDangerousMod(config, [
        'android',
        async (config) => {
            // This is a backup method if withProguardRule doesn't work as expected or for broader modification,
            // but strictly speaking, we should try to use specific mod if available.
            // However, Expo doesn't have a direct 'withProguard' mod exposed simply in all versions.
            // So let's use the standard way to append to proguard-rules.pro if it exists, 
            // or rely on the build.gradle modification if that is more robust.

            // actually, the best way for a managed workflow to add proguard rules is often via 
            // android.proguard-rules.pro file in the android directory during prebuild.

            // Let's use a simpler approach: 
            // modifying the app/build.gradle is complex.
            // Adding a file to the project works.

            // BUT, Expo has a helper for this? No, not directly for arbitrary text.
            return config;
        },
    ]);
};

// Simplified approach: Just return the config if we can't easily inject. 
// BUT WAIT, we need to solve the user's problem.
// The most reliable way in Expo Managed workflow is to use `expo-build-properties` 
// OR write to the proguard file.

const { withAndroidPlugin } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const withRazorpay = (config) => {
    return withDangerousMod(config, [
        'android',
        async (config) => {
            const projectRoot = config.modRequest.projectRoot;
            const proguardRulesPath = path.join(projectRoot, 'android', 'app', 'proguard-rules.pro');

            // The rules needed for Razorpay
            const razorpayRules = `
# Razorpay Proguard Rules
-keep class com.razorpay.** { *; }
-dontwarn com.razorpay.**
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
-keep class org.webkit.** { *; }
      `;

            if (fs.existsSync(proguardRulesPath)) {
                const currentContent = fs.readFileSync(proguardRulesPath, 'utf8');
                if (!currentContent.includes('com.razorpay')) {
                    fs.writeFileSync(proguardRulesPath, currentContent + razorpayRules);
                }
            } else {
                // If file doesn't exist (unlikely in prebuild, but possible if clean)
                // In managed flow, we might need to create it or better yet, proper standard way.
                // Attempting to write to it assuming it was generated by prebuild.
                try {
                    fs.writeFileSync(proguardRulesPath, razorpayRules);
                } catch (e) {
                    console.log("Could not write proguard rules", e);
                }
            }
            return config;
        },
    ]);
};

module.exports = withRazorpay;
